# Generated by Django 5.2.12 on 2026-04-18 09:11

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0227_alter_interface_speed_bigint'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('backup_all', models.BooleanField(default=True)),
                ('interval_minutes', models.PositiveIntegerField(default=1440)),
                ('devices', models.ManyToManyField(blank=True, to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '定时备份任务',
                'verbose_name_plural': '定时备份任务',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigBackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('filename', models.CharField(max_length=255)),
                ('config_data_txt', models.TextField()),
                ('config_data_xml', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('backup_time', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_records', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '设备备份记录',
                'verbose_name_plural': '备份信息',
                'ordering': ('-created',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('diff_content', models.TextField()),
                ('change_summary', models.CharField(max_length=255)),
                ('change_time', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_changes', to='dcim.device')),
                ('new_backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_as_new', to='netbox_config_backup.configbackuprecord')),
                ('old_backup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_as_old', to='netbox_config_backup.configbackuprecord')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '配置变更',
                'verbose_name_plural': '配置变更管理',
                'ordering': ['-change_time'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeviceConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('backup_time', models.CharField(blank=True, max_length=50, null=True)),
                ('ssh_username', models.CharField(blank=True, max_length=20, null=True)),
                ('ssh_password', models.CharField(blank=True, max_length=100, null=True)),
                ('config_data_txt', models.TextField(blank=True, null=True)),
                ('config_data_xml', models.TextField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_backups', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '备份信息',
                'verbose_name_plural': '备份设备列表',
                'ordering': ['-created'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
