# Generated by Django 5.2.12 on 2026-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configchange',
            name='status',
            field=models.CharField(default='change_first', max_length=20),
        ),
    ]
