# Generated by Django 5.2.12 on 2026-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_backup', '0002_alter_configchange_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configchange',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='configbackuprecord',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configchange',
            name='status',
            field=models.CharField(default='first_backup', max_length=20),
        ),
    ]
